# Generated by Django 3.2.19 on 2023-07-12 07:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_drink'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
    ]
