# Generated by Django 3.2.19 on 2023-07-12 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20230712_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='featured_image',
        ),
    ]
