# Generated by Django 3.2.19 on 2023-06-30 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='No_of_guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OnlineBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, unique=True)),
                ('last_name', models.CharField(max_length=20, unique=True)),
                ('reservation_datetime', models.DateField()),
                ('time', models.CharField(choices=[('10 AM - 12 AM', '10 AM - 12 AM'), ('11 AM - 1 PM', '11 AM - 1 PM'), ('12 PM - 2 PM', '12 PM - 2 PM'), ('1 PM - 3 PM', '1 PM - 3 PM'), ('2 PM - 4 PM', '2 PM - 4 PM'), ('3 PM - 5 PM', '3 PM - 5 PM'), ('4 PM - 6 PM', '4 PM - 6 PM'), ('5 PM - 7 PM', '5 PM - 7 PM'), ('6 PM - 8 PM', '6 PM - 8 PM'), ('7 PM - 9 PM', '7 PM - 9 PM'), ('8 PM - 10 PM', '8 PM - 10 PM')], max_length=60, null=True)),
                ('occassion', models.CharField(choices=[('Birthday', 'Birthday'), ('Anniversary', 'Anniversary'), ('Date night ', 'Date night '), ('Business Meal', 'Business Meal'), ('Other', 'Other')], default='Birthday', max_length=150)),
                ('table', models.CharField(choices=[('Family table', 'Family table'), ('Outdoor seating', 'Outdoor seating'), ('Table for two', 'Table for two'), ('Table on second floor (sea view)', 'Table on second floor (sea view)')], default='Family table', max_length=150)),
                ('special_request', models.TextField(blank=True, max_length=150)),
                ('approved', models.BooleanField(default=False)),
                ('no_of_guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.no_of_guest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_booking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('no_of_guest', 'reservation_datetime')},
            },
        ),
    ]
