# Generated by Django 3.2.19 on 2023-06-30 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinebooking',
            old_name='reservation_datetime',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='onlinebooking',
            unique_together={('no_of_guest', 'date')},
        ),
    ]
