# Generated by Django 3.2.19 on 2023-07-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabletime',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='numberpeople',
            name='max_people',
        ),
        migrations.RemoveField(
            model_name='numberpeople',
            name='min_people',
        ),
        migrations.RemoveField(
            model_name='numberpeople',
            name='user',
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='book_time',
            field=models.CharField(choices=[('10 AM - 12 AM', '10 AM - 12 AM'), ('11 AM - 1 PM', '11 AM - 1 PM'), ('12 PM - 2 PM', '12 PM - 2 PM'), ('1 PM - 3 PM', '1 PM - 3 PM'), ('2 PM - 4 PM', '2 PM - 4 PM'), ('3 PM - 5 PM', '3 PM - 5 PM'), ('4 PM - 6 PM', '4 PM - 6 PM'), ('5 PM - 7 PM', '5 PM - 7 PM'), ('6 PM - 8 PM', '6 PM - 8 PM'), ('7 PM - 9 PM', '7 PM - 9 PM'), ('8 PM - 10 PM', '8 PM - 10 PM')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='numberpeople',
            name='seats',
            field=models.CharField(choices=[('10 AM - 12 AM', '10 AM - 12 AM'), ('11 AM - 1 PM', '11 AM - 1 PM'), ('12 PM - 2 PM', '12 PM - 2 PM'), ('1 PM - 3 PM', '1 PM - 3 PM'), ('2 PM - 4 PM', '2 PM - 4 PM'), ('3 PM - 5 PM', '3 PM - 5 PM'), ('4 PM - 6 PM', '4 PM - 6 PM'), ('5 PM - 7 PM', '5 PM - 7 PM'), ('6 PM - 8 PM', '6 PM - 8 PM'), ('7 PM - 9 PM', '7 PM - 9 PM'), ('8 PM - 10 PM', '8 PM - 10 PM')], max_length=60, null=True),
        ),
    ]
