# Generated by Django 3.2.19 on 2023-07-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0002_auto_20230710_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberpeople',
            name='seats',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
