# Generated by Django 3.2.19 on 2023-07-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0003_alter_numberpeople_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberpeople',
            name='seats',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
